# -*- coding: utf-8 -*-
"""Daily Transactions 2 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15DINQC_BHbpHKa0K9dO-KfREq5QoSkYV
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load the dataset
df = pd.read_csv('/content/daily_transactions.csv')

# Display the first few rows of the dataset
print(df.head())  # Needs print to actually display when run as script

# Check for missing values
print(df.isnull().sum())  # Needs print to show output

# Fill or drop missing values
if 'Category' in df.columns:
    df['Category'].fillna('Unknown', inplace=True)

# Convert data types
df['Date'] = pd.to_datetime(df['Date'], errors='coerce')  # Added error handling
df['Amount'] = pd.to_numeric(df['Amount'], errors='coerce')  # In case of bad data

# Drop any rows with NaN after type conversion
df.dropna(subset=['Date', 'Amount'], inplace=True)

# Remove duplicates
df.drop_duplicates(inplace=True)

# Verify data types
print(df.dtypes)

# Summary statistics
print(df.describe())

# Distribution of transaction amounts
plt.figure(figsize=(10, 6))
sns.histplot(df['Amount'], bins=50, kde=True)
plt.title('Distribution of Transaction Amounts')
plt.xlabel('Amount')
plt.ylabel('Frequency')
plt.show()

# Transaction counts by category
if 'Category' in df.columns:
    plt.figure(figsize=(12, 6))
    sns.countplot(data=df, x='Category', order=df['Category'].value_counts().index)
    plt.title('Transaction Counts by Category')
    plt.xlabel('Category')
    plt.ylabel('Count')
    plt.xticks(rotation=45)
    plt.show()

# Transaction counts by type
if 'Type' in df.columns:
    plt.figure(figsize=(10, 6))
    sns.countplot(data=df, x='Type')
    plt.title('Transaction Counts by Type')
    plt.xlabel('Type')
    plt.ylabel('Count')
    plt.show()

# Resample data to monthly frequency
monthly_data = df.set_index('Date').resample('M')['Amount'].sum()
plt.figure(figsize=(14, 7))
plt.plot(monthly_data.index, monthly_data.values, marker='o')
plt.title('Monthly Transaction Amounts')
plt.xlabel('Month')
plt.ylabel('Total Amount')
plt.grid(True)
plt.show()

# Daily trends
daily_data = df.groupby(df['Date'].dt.date)['Amount'].sum()
plt.figure(figsize=(14, 7))
plt.plot(daily_data.index, daily_data.values, marker='o')
plt.title('Daily Transaction Amounts')
plt.xlabel('Date')
plt.ylabel('Total Amount')
plt.grid(True)
plt.show()

# Create a pivot table for correlation analysis
if 'Category' in df.columns:
    pivot_table = df.pivot_table(index='Date', columns='Category', values='Amount',
                                 aggfunc='sum', fill_value=0)

    # Calculate correlation matrix
    correlation_matrix = pivot_table.corr()

    # Plot correlation heatmap
    plt.figure(figsize=(12, 8))
    sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', linewidths=0.5)
    plt.title('Correlation Heatmap of Transaction Categories')
    plt.show()