# -*- coding: utf-8 -*-
"""Daily Transactions 1 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RWxEAlZyBfDMtsC554-aW7QsebftOoRx
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_csv("/content/daily_transactions.csv")
df.head()

df.shape
df.info()
df.isnull().sum()
df["Mode"].value_counts()
plt.figure(figsize = (12,8))
sns.countplot(data = df, x = "Mode", order =
df["Mode"].value_counts().iloc[:3].index)
plt.show()
df["Category"].value_counts()
sns.countplot(data = df, x = "Category", order =
df["Category"].value_counts().iloc[:5].index);
df["Subcategory"].unique()
plt.figure(figsize = (12,8))
sns.countplot(data = df, x = "Subcategory", order =
df["Subcategory"].value_counts().iloc[:10].index)
plt.show()
sns.countplot(data = df, x = "Income/Expense");
df["Note"].nunique()
df["Currency"].value_counts()
plt.figure(figsize = (12,8))
sns.boxplot(data = df, x = "Amount", y = "Category", order =
df["Category"].value_counts().iloc[:5].index)
plt.show()
plt.figure(figsize = (12,8))
sns.boxplot(data = df, x = "Amount", y = "Subcategory", order =
df["Subcategory"].value_counts().iloc[:10].index)
plt.show()
sns.boxplot(data = df, x = "Amount", y = "Income/Expense");
sns.scatterplot(data = df,x = "Income/Expense", y="Mode");