# -*- coding: utf-8 -*-
"""Green Destinations .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t9blEN-bYDAeR2XFdv1FpurRsQNDL5DV
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd

df = pd.read_csv("/content/green_destination.csv")
df.head()

"""#Question 1: What is the attrition rate?

In Tableau:
- Drag "Attrition" to Rows
- Use Quick Table Calculation → Percent of Total
- Show results as text or donut chart
"""

# Python calculation of attrition rate
attrition_rate = df['Attrition'].value_counts(normalize=True) * 100
attrition_rate

"""# Question 2: Does age affect attrition?

In Tableau:
- Plot bar chart of Age (binned) vs. Attrition
"""

import seaborn as sns
import matplotlib.pyplot as plt

sns.histplot(data=df, x='Age', hue='Attrition', multiple='stack', bins=10)
plt.title("Attrition by Age")
plt.show()