# -*- coding: utf-8 -*-
"""Statistics Advanced Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hPbvR0drVDTKpfELPNFWtptT22spLajJ

<a id='1'></a><center> <h3 style="background-color:orange; color:white" ><br>Telecommunication Industry Project<br></h3>

# Introduction
This Jupyter notebook is part of your learning experience in the study of applied statistics.

You will work with a data set that contains mobile phone prices and their specifications.

**Dataset Columns Information**

PID = a unique identifier for the phone model

Blue = whether the phone has bluetooth support or not

Wi_Fi = whether the phone has wifi support or not

Tch_Scr = whether the phone has touch screen support or not

Ext_Mem = whether the phone has external memory support or not

Px_h = number of pixels in the vertical axis of the phone

Px_w = number of pixels in the horizontal axis of the phone

Scr_h = height of the screen of the phone in centimetres (cm)

Scr_w = width of the screen of the phone in centimetres (cm)

Int_Mem = internal memory of the phone measured in megabytes (MB)

Bty_Pwr = maximum energy stored by the phone's battery measured in
milli-Ampere-hours (mAh)

PC = resolution of the primary camera measued in megapixels (MP)

FC = resolution of the front camera measued in megapixels (MP)

RAM = random access memory available in the phone measured in gigabytes (GB)

Depth = depth of the mobile phone measured in centimetres (cm)

Weight = weight of the mobile phone measured in grams (g)

Price = selling price of the mobile phone in rupees
"""



"""## Task 1 - Load and study the data

Import the libraries that will be used in this notebook
"""

# Load "numpy" and "pandas" for manipulating numbers and data frames
# Load "matplotlib.pyplot" and "seaborn" for data visualisation
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""Load the csv file as pandas dataframe."""

# Read in the "Dataset" file as a Pandas Data Frame
data = pd.read_csv("/content/Telecom Dataset.csv")

# Take a brief look at the data
data.head()

# Get the dimensions of the dataframe

data.shape

# Get the row names of the dataframe

data.index

# Get the column names of the dataframe

data.columns

# Look at basic information about the dataframe

data.info()

"""Observations:

There are 50 phones in the data set.

There are 17 features in the data set including the "PID" feature which is used as the row index labels.

There are no missing values in the data set.
"""



"""<center>Let's try some logical operators to filter the data.<center>

![](https://th.bing.com/th/id/R.0592084daa6518e4fae97f47217ec69e?rik=vNqmiaTVSSo54w&riu=http%3a%2f%2f2.bp.blogspot.com%2f-ujABms6N-Cg%2fTyYwShdTjnI%2fAAAAAAAAAAs%2fktPbHdifidc%2fs1600%2fLogical%2bOperators.PNG&ehk=ww1gl1HB2PcZwPQNHWRUvcQ631Q3mzyHSxL9G4zUKT4%3d&risl=&pid=ImgRaw&r=0,width=700,height=400)

## Task 2 - Obtain the logical conditions for the features "Blue", "Wi_Fi", "Tch_Scr" and "Ext_Mem"
"""

# Get the feature names of the dataframe

data.columns

# Let's tackle these features: "Blue", "Wi_Fi", "Tch_Scr", "Ext_Mem"
blue_condition = data['Blue'] == "yes"
wifi_condition = data['Wi_Fi'] == "yes"
touch_screen_condition = data['Tch_Scr'] == "yes"
ext_mem_condition = data['Ext_Mem'] == "yes"
filtered_rows = data[blue_condition & wifi_condition & touch_screen_condition & ext_mem_condition]
print(filtered_rows)

# The children want phones that have the following: Bluetooth, WiFi, touch screen and external memory support
# Create a logical condition for this situation and store the logical values as "con1"
con1 = (data['Blue'] == "yes") & (data['Wi_Fi'] == "yes") & (data['Tch_Scr'] == "yes") & (data['Ext_Mem'] == "yes")
print(con1)

"""Observations:

The features "Blue", "Wi_Fi", "Tch_Scr" and "Ext_Mem" are binary in nature.

The children want all these features, so the logical condition "con1" has been obtained accordingly.

## Task 3 - Obtain the logical conditions for the features "Px_h" and "Px_w"
"""

# Get the feature names of the dataframe
data.columns

# Let's tackle these features: "Px_h", "Px_w"
# Logical conditions for "Px_h" and "Px_w"
px_h_condition = data['Px_h'] > 2000
px_w_condition = data['Px_w'] > 1500

# Combine conditions
con2 = px_h_condition & px_w_condition

# Print logical values
print("Logical values for condition on 'Px_h' and 'Px_w':")
print(con2)

# Filter rows based on the combined condition
filtered_data = data[con2]

# Display filtered rows
print("Filtered Rows based on the conditions:")
print(filtered_data)

# Create a new feature called "Px" which stores the total resolution of the screen
data['Px'] = data['Px_h'] * data['Px_w']

# Create a histogram of the "Px" feature and also show the mean and the median
import matplotlib.pyplot as plt
import numpy as np

plt.hist(data['Px'])
plt.xlabel('Screen Resolution (Px)')
plt.ylabel('Frequency')
plt.title('Distribution of Screen Resolutions')

# Calculate and display the mean and median
mean_px = np.mean(data['Px'])
median_px = np.median(data['Px'])

plt.axvline(mean_px, color='r', linestyle='dashed', linewidth=2, label=f'Mean: {mean_px:.2f}')
plt.axvline(median_px, color='g', linestyle='dashed', linewidth=2, label=f'Median: {median_px:.2f}')

plt.legend()
plt.show()

# The children want phones that have good screen resolutions
# Consider the phones that have screen resolutions greater than or equal to the median value in the data set
# Create a logical condition for this situation and store the logical values as "con2"
data['Px'] = data['Px_h'] * data['Px_w']

median_px = np.median(data['Px'])

con2 = data['Px'] >= median_px

"""Observations:

The features "Px_h" and "Px_w" are respectively the number of pixels in the phone screen in the vertical and horizontal axes.

We created a new feature called "Px" which is the product of the features "Px_h" and "Px_w".

The median has been selected as a threshold in this case.

In case it is too strict, we can choose the mean as a threshold.

# Task 4 - Obtain the logical conditions for the features "Scr_h" and "Scr_w"
"""

# Let's tackle these features: "Scr_h", "Scr_w"

# Create a new feature called "Scr_d" which stores the length of the diagonal of the screen of the phone
data['Scr_d'] = np.sqrt(data['Scr_h']**2 + data['Scr_w']**2)

# Create a histogram of the "Scr_d" feature and also show the quartiles
# Calculate quartiles
q1 = np.percentile(data['Scr_d'], 25)
q2 = np.percentile(data['Scr_d'], 50)  # Median
q3 = np.percentile(data['Scr_d'], 75)

# Create histogram
plt.hist(data['Scr_d'], bins=10)  # Adjust 'bins' for desired granularity
plt.xlabel('Screen Diagonal Length (cm)')
plt.ylabel('Frequency')
plt.title('Distribution of Screen Sizes')

# Overlay quartiles
plt.axvline(q1, color='r', linestyle='--', label='Q1')
plt.axvline(q2, color='g', linestyle='--', label='Q2 (Median)')
plt.axvline(q3, color='b', linestyle='--', label='Q3')

plt.legend()
plt.show()

# The children want phones that have very good screen sizes
# Consider the phones that have screen sizes greater than or equal to the upper quartile value in the data set
# Create a logical condition for this situation and store the logical values as "con3"
con3 = data['Scr_d'] >= q3

"""Observations:

The features "Scr_h" and "Scr_w" are respectively the height and the width of the phone screen.

We created a new feature called "Scr_d" which is essentially the length of the screen diagonal.

The upper quartile has been selected as a threshold in this case as the children were very particular on this point.

In case it is too strict, we can choose the mean or the median as a threshold.

# Task 5 - Obtain the logical conditions for the features "PC" and "FC"
"""

# Let's tackle these features: "PC", "FC"
# Logical conditions for "PC" and "FC"
pc_condition = data['PC'] >= 8
fc_condition = data['FC'] >= 4
# Combine conditions
con3 = pc_condition & fc_condition
print(con3)
filtered_data = data[con3]
print(filtered_data)

# Create a histogram of the "PC" feature and also show the mean and the median
import matplotlib.pyplot as plt

# Calculate mean and median of the "PC" feature
mean_pc = data['PC'].mean()
median_pc = data['PC'].median()

mean_pc = np.mean(data['PC'])
median_pc = np.median(data['PC'])

# Create a histogram for the "PC" feature
plt.hist(data['PC'], bins=10, color='skyblue', edgecolor='black')
plt.title('Histogram of PC (Primary Camera)')
plt.xlabel('PC (Primary Camera MP)')
plt.ylabel('Frequency')
plt.grid(axis='y', linestyle='--', alpha=0.7)

# Show the plot
plt.show()

# Create a histogram of the "FC" feature and also show the mean and the median
# Calculate mean and median of the "FC" feature
mean_fc = data['FC'].mean()
median_fc = data['FC'].median()

# Print mean and median
print(f"Mean of 'FC': {mean_fc}")
print(f"Median of 'FC': {median_fc}")

# Create a histogram for the "FC" feature
plt.hist(data['FC'], bins=10, color='lightgreen', edgecolor='black')
plt.title('Histogram of FC (Front Camera)')
plt.xlabel('FC (Front Camera MP)')
plt.ylabel('Frequency')
plt.grid(axis='y', linestyle='--', alpha=0.7)

# Show the plot
plt.show()

# The children want phones that have good primary and front camera resolutions
# Consider the phones that have primary and front camera resolutions greater than or equal to their respective mean values
# Create a logical condition for this situation and store the logical values as "con4"
# Create the logical condition
con4 = (data['PC'] >= mean_pc) & (data['FC'] >= mean_fc)

# Print the logical values
print(con4)

# Filter rows based on the condition
filtered_phones = data[con4]

# Display the filtered rows
print(filtered_phones)

"""Observations:

The features "PC" and "FC" are respectively the resolutions of the primary camera and the front camera.

The respective means have been selected as thresholds in this case.

In case it is too strict, we can choose the respective medians as thresholds.

# Task 6 - Obtain the logical conditions for the features "Int_Mem", "Bty_Pwr" and "RAM"
"""

# Let's tackle these features: "Int_Mem", "Bty_Pwr", "RAM"
# Logical conditions for "Int_Mem", "Bty_Pwr", and "RAM"
int_mem_condition = data['Int_Mem'] >= 32
bty_pwr_condition = data['Bty_Pwr'] >= 3000
ram_condition = data['RAM'] >= 4

# Combine conditions
con5 = int_mem_condition & bty_pwr_condition & ram_condition

# Print logical values
print(con5)

# Filter rows based on the combined condition
filtered_data = data[con5]

# Display filtered rows
print(filtered_data)

# Create a histogram of the "Int_Mem" feature and also show the mean and the median
# Calculate mean and median of the "Int_Mem" feature
mean_int_mem = data['Int_Mem'].mean()
median_int_mem = data['Int_Mem'].median()

# Print mean and median
mean_int_mem
median_int_mem

# Create a histogram for the "Int_Mem" feature
plt.hist(data['Int_Mem'], bins=10, color='orange', edgecolor='black')
plt.title('Histogram of Int_Mem (Internal Memory)')
plt.xlabel('Internal Memory (GB)')
plt.ylabel('Frequency')
plt.grid(axis='y', linestyle='--', alpha=0.7)

# Show the plot
plt.show()

# Create a histogram of the "Bty_Pwr" feature and also show the mean and the median
# Calculate the mean and median of the "Bty_Pwr" feature
mean_bty_pwr = data['Bty_Pwr'].mean()
median_bty_pwr = data['Bty_Pwr'].median()

# Print the mean and median
print(f"Mean of 'Bty_Pwr': {mean_bty_pwr}")
print(f"Median of 'Bty_Pwr': {median_bty_pwr}")

# Create a histogram for the "Bty_Pwr" feature
plt.hist(data['Bty_Pwr'], bins=10, color='lightblue', edgecolor='black')
plt.title('Histogram of Bty_Pwr (Battery Power)')
plt.xlabel('Battery Power (mAh)')
plt.ylabel('Frequency')
plt.grid(axis='y', linestyle='--', alpha=0.7)

# Show the plot
plt.show()

# Create a histogram of the "RAM" feature and also show the mean and the median
# Calculate the mean and median of the "RAM" feature
mean_ram = data['RAM'].mean()
median_ram = data['RAM'].median()

# Print the mean and median
print(f"Mean of 'RAM': {mean_ram}")
print(f"Median of 'RAM': {median_ram}")

# Create a histogram for the "RAM" feature
plt.hist(data['RAM'], bins=10, color='purple', edgecolor='black')
plt.title('Histogram of RAM')
plt.xlabel('RAM (GB)')
plt.ylabel('Frequency')
plt.grid(axis='y', linestyle='--', alpha=0.7)

# Show the plot
plt.show()

# The children want phones that have good internal memory, battery power and RAM
# Consider the phones that have internal memory, battery power and RAM greater than or equal to their respective mean values
# Create a logical condition for this situation and store the logical values as "con5"
# Calculate the mean values of "Int_Mem", "Bty_Pwr", and "RAM"
mean_int_mem = data['Int_Mem'].mean()
mean_bty_pwr = data['Bty_Pwr'].mean()
mean_ram = data['RAM'].mean()

# Print the mean values
print(f"Mean of 'Int_Mem': {mean_int_mem}")
print(f"Mean of 'Bty_Pwr': {mean_bty_pwr}")
print(f"Mean of 'RAM': {mean_ram}")

# Create the logical condition
con5 = (data['Int_Mem'] >= mean_int_mem) & (data['Bty_Pwr'] >= mean_bty_pwr) & (data['RAM'] >= mean_ram)

# Print the logical values
print(con5)

# Filter rows based on the condition
filtered_phones = data[con5]

# Display the filtered rows
print(filtered_phones)

"""Observations

The features "Int_Mem", "Bty_Pwr" and "RAM" are respectively the internal memory, battery power and RAM of the phones.

The respective means have been selected as thresholds in this case.

.In case it is too strict, we can choose the respective medians as thresholds

# Task 7 - Obtain the logical conditions for the features "Depth" and "Weight"
"""

# Let's tackle these features: "Depth", "Weight"
# Logical conditions for "Depth" and "Weight"
depth_condition = data['Depth'] <= 10
weight_condition = data['Weight'] <= 300

# Combine conditions
con6 = depth_condition & weight_condition

# Print logical values
print(con6)

# Filter rows based on the combined condition
filtered_data = data[con6]

# Display filtered rows
print(filtered_data)

# Create a histogram of the "Depth" feature and also show the mean and the median
# Calculate mean and median of the "Depth" feature
mean_depth = data['Depth'].mean()
median_depth = data['Depth'].median()

# Print mean and median
print(f"Mean of 'Depth': {mean_depth}")
print(f"Median of 'Depth': {median_depth}")

# Create a histogram for the "Depth" feature
plt.hist(data['Depth'], bins=10, color='blue', edgecolor='black')
plt.title('Histogram of Depth')
plt.xlabel('Depth (mm)')
plt.ylabel('Frequency')
plt.grid(axis='y', linestyle='--', alpha=0.7)

# Show the plot
plt.show()

# Create a histogram of the "Weight" feature and also show the mean and the median
# Calculate the mean and median of the "Weight" feature
mean_weight = data['Weight'].mean()
median_weight = data['Weight'].median()

# Print the mean and median
print(f"Mean of 'Weight': {mean_weight}")
print(f"Median of 'Weight': {median_weight}")

# Create a histogram for the "Weight" feature
plt.hist(data['Weight'], bins=10, color='green', edgecolor='black')
plt.title('Histogram of Weight')
plt.xlabel('Weight (grams)')
plt.ylabel('Frequency')
plt.grid(axis='y', linestyle='--', alpha=0.7)

# Show the plot
plt.show()

# The children want phones that are light weight and slim
# Consider the phones that have depth and weight less than or equal to the respective median values in the data set
# Create a logical condition for this situation and store the logical values as "con6"
# Calculate the median values for "Depth" and "Weight"
median_depth = data['Depth'].median()
median_weight = data['Weight'].median()

# Print the median values
print(f"Median of 'Depth': {median_depth}")
print(f"Median of 'Weight': {median_weight}")

# Create the logical condition
con6 = (data['Depth'] <= median_depth) & (data['Weight'] <= median_weight)

# Print the logical values
print(con6)

# Filter rows based on the condition
filtered_phones = data[con6]

# Display the filtered rows
print(filtered_phones)

"""Observations:

The features "Depth" and "Weight" are respectively the depth of the phone and the weight of the phone.

The respective medians have been selected as thresholds in this case.

In case it is too strict, we can choose the respective means as thresholds.

# Task 8 - Subset the data based on all the logical conditions
"""

# Subset the dataframe using all the logical conditions that have been stored
# Store the subset of the dataframe as a new dataframe called "df1"
# Logical conditions
con1 = (data['Blue'] == "yes") & (data['Wi_Fi'] == "yes") & (data['Tch_Scr'] == "yes") & (data['Ext_Mem'] == "yes")
con2 = (data['Px_h'] > 2000) & (data['Px_w'] > 1500)
mean_pc = data['PC'].mean()
mean_fc = data['FC'].mean()
con3 = (data['PC'] >= mean_pc) & (data['FC'] >= mean_fc)
mean_int_mem = data['Int_Mem'].mean()
mean_bty_pwr = data['Bty_Pwr'].mean()
mean_ram = data['RAM'].mean()
con4 = (data['Int_Mem'] >= mean_int_mem) & (data['Bty_Pwr'] >= mean_bty_pwr) & (data['RAM'] >= mean_ram)
median_depth = data['Depth'].median()
median_weight = data['Weight'].median()
con5 = (data['Depth'] <= median_depth) & (data['Weight'] <= median_weight)

# Combine all logical conditions
final_condition = con1 & con2 & con3 & con4 & con5

# Subset the dataframe based on the final condition
df1 = data[final_condition]

# Display the subset of the dataframe
print(df1)

# Get the dimensions of the dataframe
# Get the dimensions of the DataFrame
rows, columns = data.shape

# Print the dimensions
print(f"Number of rows: {rows}")
print(f"Number of columns: {columns}")

# Sort the dataframe according to the "Price" feature in ascending order and display it
# Sort the DataFrame by the "Price" feature in ascending order
sorted_data = data.sort_values(by='Price', ascending=True)

# Display the sorted DataFrame
print(sorted_data)

"""Observations:

Based on all the logical conditions obtained through analysis of the features, we are left with three phones.

The most expensive of these phones is the "TYS938L" model and the least expensive is the "TVF078Y" model.

We could let the children choose from these three phones as per their preferences.

# Task 9 - Study the variability of the features in the original data set
"""

# Calculate the ratio of the standard deviation to the mean for all the numerical features in the dataframe
# Store these values in a new series wherein the rows are the features and the only column is the calculated ratio
# Name the series as "deviations"
# Select numerical features in the DataFrame
numerical_features = data.select_dtypes(include=['float64', 'int64'])

# Calculate the ratio of standard deviation to mean
deviations = numerical_features.std() / numerical_features.mean()

# Convert to a series and name it "deviations"
deviations.name = "deviations"

# Print the series
print(deviations)

# View the "deviations" series after sorting it in descending order
# Sort the "deviations" series in descending order
sorted_deviations = deviations.sort_values(ascending=False)

# Print the sorted series
print(sorted_deviations)

"""Observations:

The ratio of the standard deviation to the mean of a feature normalises it in a way.

This allows for comparison between multiple features.

The most variable feature in the original data set is the internal memory of the phones.

The least variable feature in the original data set is the number of screen pixels in the horizontal axis.

Although most features don't seem so variable, the prices of the phones are quite variable.

Feel free to investigate what could be the cause of this difference in variability.

Note: We encourage you to extend this analysis further and see what else you can find.

Note: Please refer to the official website of Python and its libraries for various Python documentations.

# Conclusion
1. We have used concepts of descriptive statistics to study and work with a data set that contains mobile phone specifications.

2. We were able to recommend three phone models to the client which she can then propose to her children.
"""

